### ISSUE TITLE
NullReferenceException in ImageGallery7DetailPage

### ISSUE THREAD

**Issue by Nukepayload2** [mrlacey/wts-vb-demos#1]
### Steps to reproduce:
1. Build and run "SplitViewMVVMLightVBDemo".
2. Open the pane of the hamburger menu and tap on "ImageGallery7". 
3. Tap on any of the images.

### Expected behavior:
Show the detail of the tapped image.

### Actual behavior:
The app crashes.
System.NullReferenceException:“Object reference not set to an instance of an object.”
ViewModel is Nothing.
   at SplitViewMVVMLightVBDemo.Views.ImageGallery7DetailPage..ctor()
   at SplitViewMVVMLightVBDemo.SplitViewMVVMLightVBDemo_XamlTypeInfo.XamlTypeInfoProvider.Activate_197_ImageGallery7DetailPage()
   at SplitViewMVVMLightVBDemo.SplitViewMVVMLightVBDemo_XamlTypeInfo.XamlUserType.ActivateInstance()

**Comment by Nukepayload2** [comment]
ImageGallery8DetailPage (in TabbedPivotMVVMLightVBDemo) has the same problem.

**Comment by mrlacey** [comment]
Good find. Fix coming soon
